### ISSUE TITLE
Video uploads requires chunking 

### ISSUE THREAD

**Issue by mmm3bbb** [desmondmorris/node-twitter#110]
Needs to follow INIT/APPEND/FINALIZE model

See link:
https://twittercommunity.com/t/uploading-video-in-node-js-always-400-media-type-unrecognized/45825/3

**Comment by nicbarker** [comment]
Was this ever looked into?

**Comment by desmondmorris** [comment]
As suggested, and documented in the link supplied, to properly upload a video, you must issue 3 separate requests to upload the video.  I will try to put together an example.  However, a helper method specifically for uploading videos, is out of scope of this library, as the functionality can be achieved with the library as it stands.

See:  https://dev.twitter.com/rest/reference/post/media/upload-init, https://dev.twitter.com/rest/reference/post/media/upload-append, https://dev.twitter.com/rest/reference/post/media/upload-finalize

**Comment by desmondmorris** [comment]
@lyzadanger added a chunked media example here https://github.com/desmondmorris/node-twitter/tree/master/examples#chunked-media.  That should do the trick
