### ISSUE TITLE
Application-only authenthication: "{ errors: [ { code: 89, message: 'Invalid or expired token.' } ] }"

### ISSUE THREAD

**Issue by jascination** [desmondmorris/node-twitter#112]
I've tried following the example in the docs, but evidently I'm doing something wrong.

I successfully retrieve a bearer token from Twitter like so:

```
  var consumer_key = twitKey;
  var consumer_secret = twitSecret;
  var enc_secret = new Buffer(consumer_key + ':' + consumer_secret).toString('base64');

  var oauthOptions = {
    url: 'https://api.twitter.com/oauth2/token',
    headers: {'Authorization': 'Basic ' + enc_secret, 'Content-Type': 'application/x-www-form-urlencoded;charset=UTF-8'},
    body: 'grant_type=client_credentials'
  };

  var bearer = getBearer();

  function getBearer(){
    request.post(oauthOptions, function(e, r, body) {
      var bod = JSON.parse(body);
      bearer = bod.access_token;
      console.log("Got a twitter Bearer token: " + bearer);
      return bearer;
    });
  }
```

This successfully gives me a bearer token. Then later on I try to use this token:

```
 var client = new Twitter({
      consumer_key: consumer_key,
      consumer_secret: consumer_secret,
      bearer_token: bearer
    });

   var params = "screen_name=twitterapi,twitter"
   var getUrl = "https://api.twitter.com/1.1/users/lookup.json?" + params;

    client.get(getUrl, function(error, tweets, response){
      if(error) console.log(util.inspect(error, false, null));;
      console.log(response);  // Raw response object.
    })
```

This results in `{ errors: [ { code: 89, message: 'Invalid or expired token.' } ] }`

Any ideas on what I'm doing wrong here?

**Comment by andreas4all** [comment]
I have the same issue. I can't put new tweet over API.

**Comment by lancew** [comment]
Hi,
I too receive this error:
```
   [ { code: 89, message: 'Invalid or expired token.' } ] 
```
 
I get this from the first example (with small addition of outputting the error):

```
var Twitter = require('twitter');
 
var client = new Twitter(
    { 
    "consumer_key" : "key",
    "consumer_secret": "secret",
    "token": "token",
    "token_secret": "secret here" 
}
);

var params = {screen_name: 'nodejs'};
client.get('statuses/user_timeline', params, function(error, tweets, response){
  if (!error) {
    console.log(tweets);
  } else {
    console.log(error);
  }
});
```
I have removed the tokens and secret.

Any thoughts?

**Comment by JSReligion** [comment]
yeah, docs not correct for version that in npm (1.2.5)
needed manual update files (twitter.js and parser.js) 
from master tree ( https://github.com/desmondmorris/node-twitter/tree/master/lib ) 
to folder in you node dirrectory ( node_modules/twitter/lib )

**Comment by desmondmorris** [comment]
This should be fixed in the latest release in npm.

**Comment by jstenner** [comment]
I'm getting [ { code: 89, message: 'Invalid or expired token.' } ] as well, and have replaced twitter.js and parser.js with the masters just in case npm is still out of date. Any ideas? Thanks!

**Comment by mjdowd** [comment]
In my case it is solved after I changed (access_token) to (access_token_key).

I hope it helps.

Regards,

Majed

**Comment by vasubits** [comment]
if your Access Token=738629462149844993-FcWHjfcucCLGEosyGGQ38qI******iC then don't forget to mention hyphen (-) followed by your USERID.

**Comment by raphaelSeguin** [comment]
Thanks @mjdowd ! It HELPS indeed !
