### ISSUE TITLE
Callback is not called if request takes a lot of time

### ISSUE THREAD

**Issue by probil** [desmondmorris/node-twitter#118]
So if I create twitter client like so:
```js
var client = new Twitter({
            consumer_key       : access['tw']['consumer_key'],
            consumer_secret    : access['tw']['consumer_secret'],
            access_token_key   : access['tw']['oauth_token'],
            access_token_secret: access['tw']['oauth_token_secret']
        });
```
and then fetch data
```js
client.get('users/show', params, function (error, user, response) {
//callback body
});
```

Callback body could be called after 20min or even few hours after the request is sent (proxy is used in my case). So, maybe it's better to add some default request timeout, for example, 30s?

If I add a timeout to requst_options it works great for me.
```js
var client = new Twitter({
            consumer_key       : access['tw']['consumer_key'],
            consumer_secret    : access['tw']['consumer_secret'],
            access_token_key   : access['tw']['oauth_token'],
            access_token_secret: access['tw']['oauth_token_secret'],
            request_options: {
                timeout: 20000
            }
        });
```

This could help other people to find why callback is not called.

**Comment by desmondmorris** [comment]
Thanks for the details here.  This brings up a good point.  We may want to make it more clear to folks that they can easily extend the Request object by using the `request_options` key.
