### ISSUE TITLE
wrong extend auth params variable

### ISSUE THREAD

**Issue by JSReligion** [desmondmorris/node-twitter#119]
https://github.com/desmondmorris/node-twitter/commit/6833c8a61e92611b3aec671a61a229ba15d2985d

lib/twitter.js        

line 64 
     consumer_secret: this.options.consumer_key,
should be actually
     consumer_secret: this.options.consumer_secret,

**Comment by probil** [comment]
Yeah! 
This fix will avoid  "Could not authenticate you." error.

Thank you @JSReligion

**Comment by desmondmorris** [comment]
Fixed!
