### ISSUE TITLE
Tweet IDs in streaming API are modified

### ISSUE THREAD

**Issue by kvakes** [desmondmorris/node-twitter#126]
I'm using `"twitter": "^1.2.5"`, Node version is 5.3.0, npm 3.3.12. Fresh install of El Capitan 10.11.2.

```
tw.stream('statuses/filter', { track: 'twitter' }, function (stream) {
  stream.on('data', function (tweet) {
    console.log(tweet.id.toString() === tweet.id_str);
  });
});
```

With the result

```
false
false
false
...
```

The problem is that numerical twitter ids exceed IEEE 754 precision, e.g.

```
parseInt('682330015925579776', 10) === 682330015925579800; // true
```

I couldn't locate the bug yet.

**Comment by neiled** [comment]
I noticed exactly the same thing, however the API docs does mention to use id_str for this reason. Still ideally fixed if possible of course though...

**Comment by dutu** [comment]
See https://dev.twitter.com/overview/api/twitter-ids-json-and-snowflake

**Comment by desmondmorris** [comment]
+1 - This is a known behavior, per the docs @dutu linked.
