### ISSUE TITLE
How do I stop a stream?

### ISSUE THREAD

**Issue by babbelnedd** [desmondmorris/node-twitter#129]
Basically title.

    client.stream(...);

I want to fetch tweets as long as a user is connected to my websocket. So I basically want to do something like

```
socket.on('connect', function(){
    client.stream()
})

socket.on('disconnect', function(){
    client.stopStream();
}
```

**Comment by omeryagmurlu** [comment]
I am interested in knowing this.

**Comment by jainsourabh2** [comment]
Same here. Please revert as I want to close the connection.

**Comment by mjw56** [comment]
Looking through the code, it looks like the stream object does [expose](https://github.com/desmondmorris/node-twitter/blob/master/lib/twitter.js#L214) a ```destroy``` method. I don't see any other way to do this, but one way I think you could do it is to keep a reference to the stream provided in the callback when you first connect. Then, whenever you want to remove it, just call ```destroy``` on that reference.

```js
var Twitter = require('twitter');
 
var client = new Twitter({
  consumer_key: process.env.TWITTER_CONSUMER_KEY,
  consumer_secret: process.env.TWITTER_CONSUMER_SECRET,
  access_token_key: process.env.TWITTER_ACCESS_TOKEN,
  access_token_secret: process.env.TWITTER_ACCESS_TOKEN_SECRET
});

var io = socketio.listen(server);
var _stream = {};

io.on('connection', function(socket) {
  startStream(socket, 'javascript');

  socket.on('myapp:search', function(term) {
    console.log('received a new search:', term);
    _stream.destroy();
  });
});

function startStream(socket, term) {
  client.stream('statuses/filter', { track: term }, function(stream) {
    _stream = stream;

    stream.on('data', function(tweet) {
      socket.emit('tweet', tweet.text);
    });
   
    stream.on('error', function(error) {
      throw error;
    });
  });
}
```

**Comment by togiberlin** [comment]
`stream.destroy();` will do it
