### ISSUE TITLE
Cannot load https://userstream.twitter.com/1.1/user.json. Response for preflight has invalid HTTP status code 400

### ISSUE THREAD

**Issue by johnRivs** [desmondmorris/node-twitter#133]
I'm using Chrome. Installed the package via npm and used browserify.

I've followed the instructions and I always get `cannot load https://userstream.twitter.com/1.1/user.json. Response for preflight has invalid HTTP status code 400` 

In fact, I've tried other packages and I get the same error. I can use curl from the command line to consume this endpoint, the one Twitter gives me from their OAuth signature generator. 

Also, right before that message, it shows `OPTIONS https://userstream.twitter.com/1.1/user.json`

Is it because I'm testing locally?

**Comment by a7madgamal** [comment]
I have this issue too, someone please respond

**Comment by desmondmorris** [comment]
A similar issue in the `twit` package alludes to the fact that it may be impossible to make this request from Chrome.

https://github.com/ttezel/twit/issues/234#issuecomment-177370065
