### ISSUE TITLE
the library assumes the access token is already taken but cannot be used for obtaining the token

### ISSUE THREAD

**Issue by NikosEfthias** [desmondmorris/node-twitter#134]
the library assumes the access token is already taken but cannot be used for obtaining the token

**Comment by NikosEfthias** [comment]
how to get access token for the first time by this library

**Comment by desmondmorris** [comment]
Hi @NikosEfthias, this is addressed here  - https://github.com/desmondmorris/node-twitter#quick-start.  Obtaining access tokens is out of scope of this library at the moment.
