### ISSUE TITLE
Using Proxy Functionality with HTML Implementation

### ISSUE THREAD

**Issue by nrickles3** [desmondmorris/node-twitter#144]
I built a JavaScript module that I want to run with an HTML button locally. I used browserify to allow the HTML file to use modules like require, but I am receiving this error:

Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'null' is therefore not allowed access. The response had HTTP status code 400. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

I can not find a concrete answer online on how to approach this issue, but I was wondering if the proxy functionality of this module can help me out. From what I have read, this issue has been solved using the XMLhttprequest object and CORS, but if possible I would like to avoid that. If the proxy functionality is the solution, what should I put as my proxy?

If there is anything else I can inform you of, please let me know as I am very new to JavaScript/HTML. Thank you.

**Comment by desmondmorris** [comment]
@nrickles3 I do not think using a proxy in this situation is the right move.  If I am understanding your problem here, I would affirm that CORS would be the right way to go here.
