### ISSUE TITLE
need more then 100 tweet result

### ISSUE THREAD

**Issue by isoftmaster** [desmondmorris/node-twitter#146]
i tried tweet search but according to twitter api count limit is 100 per page

```
client.get('search/tweets', {q: 'node.js'}, function(error, tweets, response){
  console.log(tweet.length)
});
```
output 
100

is there any way to can count total tweet by a username with a hash in specific day 
eg: 
#ThingsiJustLove from:@xyz_user on 26-apr-2016
i want total number of tweets posted by this user with this hashtag in specific date

if anyone have any idea please share

**Comment by desmondmorris** [comment]
@isoftmaster unfortunately, this is a limitation of the API.  

> The number of tweets to return per page, up to a maximum of 100

See: https://dev.twitter.com/rest/reference/get/search/tweets#api-param-search_count

You will have to do your own paging here to get all of the results.  The `until`, `since_id` and `max_id` filters should be helpful.
