### ISSUE TITLE
Twitter streams deletes (and other message types)

### ISSUE THREAD

**Issue by chmac** [desmondmorris/node-twitter#153]
First off, thanks for this package, makes working with the twitter streaming api a breeze, saved us a ton of time. 👍

I was blindly saving all the streamed messages to the database and found some weirdness. Eventually tracked it down to [this](https://dev.twitter.com/streaming/overview/messages-types#status_deletion_notices_delete) in the twitter docs. Twitter will stream tweets and also `delete` commands and other message types.

I (falsely) assumed from the `console.log(tweet.text)` in the example, that the `.on('data', fn)` would only receive payloads of an actual tweet. Maybe we can add something to the docs to help folks who (like me) are just starting out with the streaming API. What do you think?

Happy to work on a PR if you think it'd be a useful change.

**Comment by desmondmorris** [comment]
Thats great to hear!

+1 to the suggested change.  If you open the PR we will get it merged

**Comment by chmac** [comment]
PR #171.
