### ISSUE TITLE
Twitter user authentication for Twitter applications 

### ISSUE THREAD

**Issue by apasrini** [desmondmorris/node-twitter#158]
I would need to understand if Twitter rest apis or node-twitter node module does allow users to authenticate twitter applications. To clearly state,

I would need to use single application and every twitter user need to authenticate (providing user/pass of twitter) to use that application ? Is this possible or supported from twitter ?

**Comment by apasrini** [comment]
Hello, any update on this question ? Would need this reply as soon as possible

**Comment by neeeeds** [comment]
hi mate, i might be late but i think that this is what are you searching for : 

https://www.npmjs.com/package/passport-twitter

**Comment by desmondmorris** [comment]
I am also late.  Thanks @neeeeds.  You can achieve this by building out the oauth flows yourself or using something like passport as suggested.  The passport route would be the easiest IMO.
