### ISSUE TITLE
Navigating REST results 

### ISSUE THREAD

**Issue by klaaz0r** [desmondmorris/node-twitter#161]
I am working with de node-twitter lib and you guys did a really good job! but is there a way to interact with the cursor in de REST api? for example when I have a query  and receive a set of tweets I get:

```
  "search_metadata": {
    "completed_in": 0.044,
    "max_id": 736866964476305408,
    "max_id_str": "736866964476305408",
    "next_results": "?max_id=736864607961124864&q=max%20verstappen&include_entities=1",
    "query": "max+verstappen",
    "refresh_url": "?since_id=736866964476305408&q=max%20verstappen&include_entities=1",
    "count": 15,
    "since_id": 0,
    "since_id_str": "0"
  }
```

Is there a possibility to navigate to the next results with node-twitter or should I implement my own functionality?

**Comment by desmondmorris** [comment]
Not automatically unfortunately.  You would need to build the next request on your own.  You will probably just need to convert the `next_results` property to an object and pass it as params
