### ISSUE TITLE
401 for streaming API

### ISSUE THREAD

**Issue by alexellis** [desmondmorris/node-twitter#165]
With valid (verified) secrets and keys and token in config.json, I can't see why this is giving me 401.

Time on server is up to date and in UTC timezone.

Please advise. 

```
npm init -y
npm i twitter
```

```
"use strict"
var Twitter = require('twitter');
let config = require('./config.json');

var client = new Twitter(config.twitter);

var stream = client.stream('statuses/filter', {track: 'EURO2016'});
stream.on('data', function(tweet) {
  console.log(tweet.text);
});


stream.on('error', function(e) {
  console.error(e);
  console.error(e.stack);

});
```

**Comment by desmondmorris** [comment]
@alexellis can you paste the error you are getting here?  Also, would be helpful to see what the contents of your config.twitter property is.  You can remove the secure bits of course.

**Comment by alexellis** [comment]
User error - although I did eventually get 420 errors (too many re-connections)

How can you develop code and not re-connect often?

**Comment by desmondmorris** [comment]
Sounds like you may be experiencing rate limiting.  Give this a read -https://dev.twitter.com/rest/public/rate-limiting

**Comment by alexellis** [comment]
Yes it definitely is rate limiting. How do you work on the project without re-connecting? It doesn't take much to get a cool-off period.

**Comment by robbiegleeson** [comment]
Interesting, I'm getting the very same error and it's not a rate limiting issues. I'm using `thunkify` to wrap the request and then bid the calls likes so...
`
function createTwitterClient(account) {
    const client = thunkifyClient(new Twitter({
        consumer_key: account.payload.consumerKey,
        consumer_secret: account.payload.consumerSecret,
        access_token_key: account.payload.accessTokenKey,
        access_token_secret: account.payload.accessTokenSecret,
    }));

    return client;
}
`

and the `thunkifyClient()` looks like: 
`
function thunkifyClient(client) {
    return {
        get: thunkify(client.get.bind(client)),
        post: thunkify(client.post.bind(client)),
        stream: thunkify(client.stream.bind(client)),
    };
}
`

Once I have thank set up I pass in my client and try to make the following request:

`
function searchStream(client) {
    co(function *() {
        console.log('searchStream');

        let res = yield client.stream('statuses/filter', {track: 'Dublin'});
        res.on('data', function (tweet) {
            console.log(tweet);
        });

    }).catch(function (err) {
        console.log(err);
    });
}
`

Which returns a 401 error:
`
Error: Status Code: 401
    at Request.<anonymous> (/vagrant/node_modules/twitter/lib/twitter.js:226:30)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at Request.onRequestResponse (/vagrant/node_modules/request/request.js:977:10)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:419:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:103:23)
    at TLSSocket.socketOnData (_http_client.js:309:20)
    at emitOne (events.js:77:13)
`

Any suggestions?

**Comment by hellsinglord22** [comment]
The time on the server was wrong. I put the correct one, with the following shell command:
`date +%T -s "15:47:10"` and boom its working . 
so give it a try . :)

**Comment by ChristianCSE** [comment]
wow I didn't realize how recent this posting is. I'm also receiving the same 401 status error

**Comment by SherlockStd** [comment]
Yeah still not working :(

**Comment by Kylew1992** [comment]
Still not working

**Comment by iDaN5x** [comment]
Having the same issue... this is my code:
```
const Twitter = require('twitter'),
           config = require('./config.json');

let twitter = new Twitter(config.twitter);

let stream = twitter.stream('statuses/filter', {track: 'Israel'})

stream.on('data', tweet => {
  console.log(tweet.text);
});

stream.on('error', error => {
  console.log(error);
});
```

I'm using application only based authentication, which freshly generated credentials...

**Comment by mdata2** [comment]
any resolution on this error? @alexellis

**Comment by iDaN5x** [comment]
@mdata2 I found out that application-level authentication does not support the streaming API.
I'm suspecting that this is the cause in your case too.

**Comment by arpitha-alur** [comment]
> The time on the server was wrong. I put the correct one, with the following shell command:
> `date +%T -s "15:47:10"` and boom its working .
> so give it a try . :)

how do I get to know if time on the server is wrong ? And where do I execute the command on windows OS ? on the command line terminal ?
