### ISSUE TITLE
What are the steps needs to get a user_timeline for a private user

### ISSUE THREAD

**Issue by rlavoie** [desmondmorris/node-twitter#168]
What are the steps needed to get a user_timeline for a private user?
Do I need to provide the lib with a users password?

**Comment by msmuenchen** [comment]
No, just use your normal API credentials. Beware, you will need the access_token from a user who follows the private user.

**Comment by desmondmorris** [comment]
@rlavoie this is correct.  You will need the API credentials from the particular user to do so.
