### ISSUE TITLE
code: 215, message: 'Bad Authentication data.'

### ISSUE THREAD

**Issue by wdk122** [desmondmorris/node-twitter#176]
I've tried running the code below, with my Twitter handle and one of its apps' keys and secrets:

```javascript
var Twitter = require('twitter');
 
var client = new Twitter({
  consumer_key: '',
  consumer_secret: '',
  access_token_key: '',
  access_token_secret: ''
});
 
var params = {screen_name: 'nodejs'};
client.get('statuses/user_timeline', params, function(error, tweets, response){
  if (!error) {
    console.log(tweets);
  }
});
```

I get error code 215 after running this. Any suggestions?

**Comment by lyzadanger** [comment]
I am also getting the same response code. I tried regenerating my keys. No dice.

**Comment by lyzadanger** [comment]
@wdk122 I thought I was running into this also today, but ultimately realized it was my own error. Did you happen to try the following?:

* Regenerate all of your keys and try again
* Check your copy-and-past accuracy (this was where I messed up—one of my string values had an erroneous space character in it).

Did you look at the full `error` object? Might have some clues in it.

**Comment by wdk122** [comment]
It was a bug on my end. Closing the issue.
