### ISSUE TITLE
multiple screen_name(s)

### ISSUE THREAD

**Issue by PaulieScanlon** [desmondmorris/node-twitter#181]
Hi, i'm able to lookup a single screen_name by doing the following:

var params = {
  screen_name: statData.votes[0].twitter_username
}

client.get('users/lookup', params, function(err, data, res) {
  console.log(params);
  if(err){
    callback(err, null);
    return
  }
  console.log("data.name: "+ data[0].name);
  console.log("data.geo_enabled: "+ data[0].geo_enabled);
  console.log("data.location: "+ data[0].location);
});

But i'm trying to work out how to make a single get request for up to 100 screen_name(s). or does this params var only accept a single screen_name ?

Ideally screen_name in the params var would be an array of up to 100 users, probably created dynamically in a loop, for instance 

screen_name: statData.votes[i].twitter_username

Are you able advise?

Thanks in advance!

Paulie

**Comment by desmondmorris** [comment]
@PaulieScanlon this is in fact supported by the API. See: https://dev.twitter.com/rest/reference/get/users/lookup.  Either via the `screen_name` or `user_id` properties.

For `screen_name`:

> A comma separated list of screen names, up to 100 are allowed in a single request. You are strongly encouraged to use a POST for larger (up to 100 screen names) requests.

For `user_id`

> A comma separated list of user IDs, up to 100 are allowed in a single request. You are strongly encouraged to use a POST for larger requests.
