### ISSUE TITLE
Sending direct messages?

### ISSUE THREAD

**Issue by jlai79** [desmondmorris/node-twitter#188]
Is it possible to send direct messages uusing node-twitter? Do you have an example how to do that?

**Comment by desmondmorris** [comment]
Yup you can.  You can make any available request documented in the API - https://dev.twitter.com/rest

```
var Twitter = require('twitter');

var client = new Twitter({
  consumer_key: '',
  consumer_secret: '',
  access_token_key: '',
  access_token_secret: ''
});

var params = {
  screen_name: 'nodejs',
  text: 'Hello World'
};
client.post('direct_messages/new', params, function(error, message, response) {
  if (!error) {
    console.log(message);
  }
});
```

See: https://dev.twitter.com/rest/reference/post/direct_messages/new

**Comment by jlai79** [comment]
And if that doesn't work? I don't get any errors. Posting tweets and retweets work as expected.

**Comment by eorroe** [comment]
Hey any idea how to do the same with the new direct_messages api: https://dev.twitter.com/rest/reference/post/direct_messages/events/new

What you posted works but with the new api, I keep getting authentication error code 32 (https://dev.twitter.com/overview/api/response-codes)

Here's an article that explains what's happening with a php library, not sure what node-twitter does: https://imbuzu.wordpress.com/2014/05/14/fixing-error-code-32-when-using-the-twitter-api/

**Comment by dfliess** [comment]
Hi @eorroe did you solved this issue ?

**Comment by eorroe** [comment]
Unfortunately not @dfliess Were you able to figure it out?

**Comment by dfliess** [comment]
yes @eorroe with this https://github.com/desmondmorris/node-twitter/pull/230, although we receive an error see my comment.

**Comment by hrivera2014** [comment]
For the code shown here we receive the error:
[ { code: 220,
    message: 'Your credentials do not allow access to this resource.' } ]

**Comment by pedroaf0** [comment]
something change?
i get this error message:
[ { code: 34, message: 'Sorry, that page does not exist.' } ]

**Comment by amj4kor** [comment]
@pedroaf0 were you able to solve this?

**Comment by pedroaf0** [comment]
@amj4kor I changed the module. I started using twit.
is more up to date. https://github.com/ttezel/twit
I have this can help you: https://gist.github.com/pedroaf0/be121249708800e6c0dc8fd8129e4fff
