### ISSUE TITLE
Browser usage

### ISSUE THREAD

**Issue by Lichwa** [desmondmorris/node-twitter#189]
I'm really confused, is it possible to use this library directly from browser? Every request I'm trying to make  ends with:

```
XMLHttpRequest cannot load https://api.twitter.com/1.1/favorites/list.json?screen_name=nodejs. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'MY_URL_HERE' is therefore not allowed access. The response had HTTP status code 400.
```

This suggests that it's only usable on external node server, but I haven't found anything to confirm that.

**Comment by YoruNoHikage** [comment]
This is due to Twitter not accepting requests sent from browser. The only way to do this is enabling CORS which they don't want to do for many reasons I think. There is more informations about it [on MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS#Preflighted_requests).

**Comment by desmondmorris** [comment]
@Lichwa, @YoruNoHikage is correct here.  Twitter does not support CORS https://twittercommunity.com/t/will-twitter-api-support-cors-headers-soon/28276/1
