### ISSUE TITLE
connect ETIMEDOUT 10.10.34.36:443

### ISSUE THREAD

**Issue by ali-mahmoodvand** [desmondmorris/node-twitter#191]
my connection and keys is right but i get this error from user_timeline

{ [Error: connect ETIMEDOUT 10.10.34.36:443]
  code: 'ETIMEDOUT',
  errno: 'ETIMEDOUT',
  syscall: 'connect',
  address: '10.10.34.36',
  port: 443 }

**Comment by desmondmorris** [comment]
@ali-mahmoodvand if this is still an issue for you, please provide more details if possible.  It does seem like a network issue however.

Closing for now

**Comment by rfwn** [comment]
this error is caused by axios, in a different project and different connection urls, it still gives this same error with the same ip address
