### ISSUE TITLE
Unable to get media Object in a re-tweet JSON response.

### ISSUE THREAD

**Issue by dpz3579** [desmondmorris/node-twitter#199]
Hi i'm trying to re-tweet few other handler's tweets, but when i fetch the tweet of my channel,
earlier i was able to get the media object with media-url in the JSON response,

but now, 
when i do that i'm unable to get the media in response JSON.

````
"entities": {
    "media": [
        {
            "id": 808263278958784500,
            "id_str": "808263278958784513",
            "media_url": "http://pbs.twimg.com/media/CzeHK3tUsAEIWP_.jpg",
            "media_url_https": "https://pbs.twimg.com/media/CzeHK3tUsAEIWP_.jpg",
            "url": "https://t.co/DfdkTzy0UN",
            "display_url": "pic.twitter.com/DfdkTzy0UN",
            "expanded_url": "https://twitter.com/dpz3579/status/808263298118320129/photo/1",
            "type": "photo",
        }
    ]
}
````

Sometimes some of my own tweet do not have media as response.
can you please check & let us know.

Thanks.

**Comment by desmondmorris** [comment]
@dpz359 this seems like an issue with the api itself.  See: https://twittercommunity.com/t/missing-media-property-in-entities/70388.  It suggests passing `tweet_mode: 'extended'` with the request.

See recent tweet changes: https://dev.twitter.com/overview/api/upcoming-changes-to-tweets

I will reopen if this does not answer the question here
