### ISSUE TITLE
Getting media type unrecognized when uploading an image

### ISSUE THREAD

**Issue by otusweb** [desmondmorris/node-twitter#212]
I'm am running into issues uploading images (posting simple tweet does not cause any issue).

here is my code, note that the first step is downloading the image from S3:

     var Twitter = require('twitter'),
     requestP = require('request-promise-native');

     var twitterConfig = config.twitter;
        twitterConfig.access_token_key = tweet.accessToken;
        twitterConfig.access_token_secret = tweet.accessTokenSecret;
        var twitter;

        // first get the image data
        var promise = requestP(tweet.imageURL)
          .then(imageData => {
            //then the image first
            twitter = new Twitter(twitterConfig);
            return twitter.post("media/upload", {
              media: imageData
            }, function (error, tweets, response) {
              if (!error) {
                console.log(tweets);
              }
            });
          });

I'm getting the following error:"media type unrecognized"

I downloaded the image manually from S3, and it seems valid so I'm unsure what is the issue.

**Comment by otusweb** [comment]
Figured out what the issue is. The data I was sending was not encoded correctly. Hence twitter not recognizing it.

**Comment by chovy** [comment]
I ran into that issue. I wrapped it in try/catch with JSON.parse.
