### ISSUE TITLE
#Streaming: 

### ISSUE THREAD

**Issue by ImSuriya** [desmondmorris/node-twitter#214]
Hi,

could some one help me to get below my queries?
1. i want to get latitude and longitude of tweets  
2. how to get retweets via stream pipe.?
          am trying to get some curated data. i believe that i can able to get it from Retweets. so i want to get retweets and latitude/longitude details of retweets as well.

clearly, i want to get retweet from below sreaming api call
client.stream('statuses/filter', {track: 'javascript'}, function(stream) {
  stream.on('data', function(event) {
    console.log(event && event.text);
  });
 
  stream.on('error', function(error) {
    throw error;
  });
});

i tried like below:
**event.user.retweeted_status
event.user.retweeted_status.id        both showing [object object] or undefined**

its very urgent guys

many thanks for any help

**Comment by jschnurr** [comment]
Each response from the API is a [Tweet](https://dev.twitter.com/overview/api/tweets) object.  For retweets, there is a Tweet object embedded on the property **retweeted_status**.

Locations are properties of Tweet objects; a **coordinates** property (lat/long), or a **place** property (see [docs](https://dev.twitter.com/overview/api/places)).  

The code below selects either the event object itself (for regular tweets), or the content of the retweeted_status property (for retweets).  Then, it returns the coordinates or place, if either exists.

``` javascript
client.stream('statuses/filter', {
    track: 'js'
}, function(stream) {
    stream.on('data', function(event) {
        var tweet = event.retweeted_status || event;
        if (tweet.coordinates || tweet.place) {
            var result = {
                id_str: tweet.id_str,
                coordinates: tweet.coordinates,
                place: tweet.place
            };
            console.log(JSON.stringify(result));
        }
    });
});
```
Many tweets have neither coordinates nor a place.  For those that do, here's the result:

``` json
{
    "id_str": "850133276761128960",
    "coordinates": null,
    "place": {
        "id": "6921f63daeee899a",
        "url": "https://api.twitter.com/1.1/geo/id/6921f63daeee899a.json",
        "place_type": "city",
        "name": "Saquarema",
        "full_name": "Saquarema, Brasil",
        "country_code": "BR",
        "country": "Brasil",
        "bounding_box": {
            "type": "Polygon",
            "coordinates": [
                [
                    [-42.681126, -22.940607],
                    [-42.681126, -22.804081],
                    [-42.368096, -22.804081],
                    [-42.368096, -22.940607]
                ]
            ]
        },
        "attributes": {}
    }
}
```

**Comment by ImSuriya** [comment]
wow man.. thanks you save my id @jschnurr . 
is that any possibility to block profanity words with current twitter api version.
actually i started working on it.

Thank you :baby:
