### ISSUE TITLE
GET users/lookup doesn't work properly

### ISSUE THREAD

**Issue by karuppiah7890** [desmondmorris/node-twitter#218]
I get this error : 
```js
[ { code: 17, message: 'No user matches for specified terms.' } ]
```
When I use `twit` npm module with the same code, I have no issues. I don't know what the problem is. This is a sample of the code : 

```js
T.get('users/lookup', { user_id : ids })
 .then((result)=>{
 //code 
 })
 .catch((err) => {
  //code
 });
```
And I send 100 ids and Twitter recommends to use POST, but the above code doesn't even if it's `T.post()` and I get the same old error.

But all works fine if I use `twit` package. But `twit` has some dirty issues with Promise rejections when errors occur. `twit` includes errors in the resolved result rather than rejecting it.

**Comment by trazek** [comment]
I am also experiencing this but with less ids. I am making sure to encode the ids (separate by %2C). If I don't encode the ids, it only looks up the first id given in the list

**Comment by karuppiah7890** [comment]
@desmondmorris Any idea why this happens ?

**Comment by karuppiah7890** [comment]
@trazek I don't get you. We are just supposed to use arrays right ?

**Comment by karuppiah7890** [comment]
How come you encode the ids ? when you have to pass it to the library as an array in the options

**Comment by dandv** [comment]
This library is no longer maintained.

[twitter-lite](https://github.com/draftbit/twitter-lite/blob/d3cb8f236787a4f443b693e5a75a6db424388bd0/twitter.test.js#L256) has a test specifically for `users/lookup`.
