### ISSUE TITLE
ES6 syntax examples, specifically retweet 🐦

### ISSUE THREAD

**Issue by spences10** [desmondmorris/node-twitter#219]
Hi, thanks for this great package, I have switched to this from `twit` as it appears to be being maintained, plus I liked the auto response email sent when I used the package, nice touch 👌 

I'm pretty new to using the Twitter API and JavaScript developement in general so I'm not sure if this is the best place to ask this so feel free to direct me to any other resources.

My issue, I have used the retweet function in `twit` and it looks pretty similar in [this package](https://github.com/desmondmorris/node-twitter/tree/master/examples#tweet), I have made a search function with ES6 syntax which works fine, here:

```javascript
import Twiter from 'twitter'
import config from '../config'
import {
  rando
} from './helpers'
import params from './parameters'

const client = new Twiter(config.twitter)

const searchResult = async () => {
  let res
  try {
    res = await client.get('search/tweets', params)
  } catch (err) {
    console.log('error = ', err)
  }
  return rando(res.statuses).id_str
}

export default searchResult

```

So I can search and return tweet id's I'd like to retweet, I have so far tried several different ways to retweet, all of which I get a response object from, but the account doesnt retweet it, am I missing something? Here's the code:

```javascript
import Twiter from 'twitter'
import config from '../config'
import searchId from './search'
import params from './parameters'

const client = new Twiter(config.twitter)

 const retweet = async () => {
   let res
   try {
     res = await client.post(`statuses/retweet/${searchId}`)
   } catch (err) {
     console.log('ERR :', err)
   }
   console.log('RES :', res)
 }

// const retweet = () => {
//   client.post(`statuses/retweet/${searchId()}`, (error, tweet, response) => {
//     if (!error) {
//       console.log('TWEET================', tweet)
//     } else {
//       console.log('TWEET: ', tweet)
//       // console.log(JSON.stringify(response))
//     }
//   })
// }

// const retweet = () => {
//   client.post('statuses/retweet/:id', {
//     id: searchId
//   }, function (err, response) {
//     if (response) {
//       console.log('RETWEETED!', ' Query String:', params)
//     }
//     // if there was an error while tweeting
//     if (err) {
//       console.log('RETWEET ERROR! Duplication maybe...:', err, 'Query String:', params)
//     }
//   })
// }

export default retweet
```

As I stated earlier the three examples here all return a `response` object but none of them seem to actually retweet, I'm probably missing something glaringly obvious or fundamental so please feel free to correct me 😄 

Any help greatly appreciated  

Thanks

**Comment by chovy** [comment]
I have not tried this but here's their example:

```
var tweetId = 'XXXXX';
client.post('statuses/retweet/' + tweetId, function(error, tweet, response) {
  if (!error) {
    console.log(tweet);
  }
});
```

If you want to use promises you could try this (untested):


	doTweet(opts){
	  return new Promise((resolve, reject) => {
	  	client.post('statuses/retweet/' + tweetId, function(err, tweet, res) {
	  	if (err) return reject(err);
	  	resolve(res); // not sure what `tweet` is here but you might want to return that instead?
	  });
	}

	doSomething()
	  .then(doTweet)

**Comment by spences10** [comment]
Hey @chovy thanks for the reply 👍 

I have tried the first example from the documentation and it does return a `response` object as does the async block I have used but none of the three examples actually re-tweet

I'll try the promise example too and let you know how it goes 👍

**Comment by spences10** [comment]
Just noticed you're not sure on what `tweet` is, what I used to take a look at the `response` JSON was [ExtensionJSON Viewer Awesome](https://chrome.google.com/webstore/detail/json-viewer-awesome/iemadiahhbebdklepanmkjenfdebfpfe) thats gives you a pretty output, like so:

![image](https://cloud.githubusercontent.com/assets/234708/25062961/459f759e-21cf-11e7-8b9e-cc96d07efbd0.png)

I was under the impression that the re-tweet is done

**Comment by chovy** [comment]
I would assume the response is the full response from the operation will the tweet is just the created retweet. Does it still not work?

**Comment by chovy** [comment]
OH I just thought of another issue I had. Always use `.id_str` not `.id` -- javascript doesn't handle twitter ids numbers properly.

**Comment by spences10** [comment]
Hey @chovy thanks for trying to help :+1:, I do use `.id_str` in the `search.js` module, it's in the first block of code posted.

![image](https://cloud.githubusercontent.com/assets/234708/25476533/6200bb1e-2b32-11e7-8fc3-35075bf5cd79.png)

I import that module, to the retweet module

![image](https://cloud.githubusercontent.com/assets/234708/25476610/9fe1e728-2b32-11e7-80bf-a96a9a1ac955.png)

I don't think that's the issue (I'm not certain that's why I'm posting an issue) as I can call `searchId` and console log it with a string Id each time.

Any help still greatly appreciated, @desmondmorris is this project going to support the "new" syntaxes?

**Comment by spences10** [comment]
:upside_down_face: hey @desmondmorris feel free to open your own issue to resolve this, I'm no longer interested in it being resolved.

Many thanks :+1:
