### ISSUE TITLE
user streaming

### ISSUE THREAD

**Issue by DusterTheFirst** [desmondmorris/node-twitter#234]
how would I use the streaming API to detect when a user posts,

I have 
```js
Twitter.stream('statuses/filter', { track: '@dusterthesecond' }, function (stream) {
    stream.on('data', function (tweet) {
        console.log(tweet.text);
    });

    stream.on('error', function (error) {
        console.log(error);
    });
});
```
but that only tracks tweets that mention `@dusterthesecond`

**Comment by JulienSol** [comment]
Hi,

The [documentation](https://dev.twitter.com/streaming/overview/request-parameters#follow) allow you to pass a `follow` param.
> The stream will then contain :
>
> - Tweets created by the user.
> - Tweets which are retweeted by the user.
> - Replies to any Tweet created by the user.
> - Retweets of any Tweet created by the user.
> - Manual replies, created without pressing a reply button (e.g. “@twitterapi I agree”).
> 
> The stream will not contain:
> 
> - Tweets mentioning the user (e.g. “Hello @twitterapi!”).
> - Manual Retweets created without pressing a Retweet button (e.g. “RT @twitterapi The API is great”).
> - Tweets by protected users.

I think you can try this : 
```JS
let user_id = 3997909817;
Twitter.stream('statuses/filter', { follow: user_id },(stream) => {
    stream.on('data', (tweet) => {
        console.log(tweet.text);
    });

    stream.on('error', function (error) {
        console.log(error);
    });
});
```

If you only want : 

> - Tweets created by the user.
> - Tweets which are retweeted by the user.
> - ~~Replies to any Tweet created by the user.~~
> - ~~Retweets of any Tweet created by the user.~~
> - Manual replies, created without pressing a reply button (e.g. “@twitterapi I agree”).

```JS
let user_id = 3997909817;
Twitter.stream('statuses/filter', { follow: user_id },(stream) => {
    stream.on('data', (tweet) => {
        if(tweet.user.id === user_id) {
            console.log(tweet.text);
        }
    });

    stream.on('error', function (error) {
        console.log(error);
    });
});
```

**Comment by DusterTheFirst** [comment]
can I make it follow multiple twitters?

EDIT: yes, seperate by commas
