### ISSUE TITLE
Error message (code 89): Invalid or expired token

### ISSUE THREAD

**Issue by jtiscione** [desmondmorris/node-twitter#237]
I'm trying the very first example in README.md:
```javascript
var Twitter = require('twitter');
var credentials = require(__dirname+"/credentials.json");

var client = new Twitter(credentials);

var params = {screen_name: 'nodejs'};
client.get('statuses/user_timeline', params, function (error, tweets, response) {
    if (!error) {
        console.log(tweets);
    } else {
        console.error(error);
    }
});
```
I'm getting this error:

`[ { code: 89, message: 'Invalid or expired token.' } ]`

None of the other endpoints work either.
This is a bug in this module, not any sort of issue with my API key. If I change the first line to

```javascript
var Twitter = require('twit')
```

and use the "twit" module instead, everything works perfectly.

**Comment by JulienSol** [comment]
Hello, what is inside your `credentials.json` ?
Twit and Twitter packages doesn't have same keys options.
Twit package keys options:
```JS
  consumer_key: '',
  consumer_secret: '',
  access_token: '',
  access_token_secret: ''
```
Twitter package keys options:
```JS
  consumer_key: '',
  consumer_secret: '',
  access_token_key: '',
  access_token_secret: ''
```

**Comment by jtiscione** [comment]
Ah, that was it! Thanks!
