### ISSUE TITLE
{ errors: [ { code: 32, message: 'Could not authenticate you.' } ] }

### ISSUE THREAD

**Issue by riatzukiza** [desmondmorris/node-twitter#245]
On every end point I try, I get this result, I have regenreated all my keys multiple times and have write permission activated.

**Comment by riatzukiza** [comment]
Found my problem, it is code I was foolishly using involving an addition to `Object.prototype`, I will close if that is all there is.

**Comment by robertmain** [comment]
I'm running into this right now and it's driving me mad. What do you mean you were using `Object.prototype`?

**Comment by DCKT** [comment]
@robertmain Hey I got the same problem and it was in fact a problem with `dotenv`, I tried without and it works well 

EDIT : It was a typo in the `dotenv` config

**Comment by robertmain** [comment]
I fixed it, I think I was using the wrong variable names for the token in the end
