### ISSUE TITLE
Can't retrieve more than 100 results from search term

### ISSUE THREAD

**Issue by khuslen** [desmondmorris/node-twitter#260]
I want to perform a search with a specified search term and retrieve all the tweets found in order to process them. Ideally, I'd like to have 1000's of tweets being returned but I can only ever get 15 or 100 when using the following two pieces of code.

The Twitter documentation (Here: [https://developer.twitter.com/en/docs/basics/rate-limits](url) ) indicates that I should be able to get at least 180 results.

```
    var search = req.params.searchTerm;
    client.get('search/tweets', {q: search}, function(error, tweets, response) {  
        if (!error) {
            console.log(tweets.statuses.length); // Always displays 15
        }
    });
```

```
    var search = 'https://api.twitter.com/1.1/search/tweets.json?q='
               + req.params.searchTerm + '&count=180';
    client.get(search, function(error, tweets, response) {  
        if (!error) {
            console.log(tweets.statuses.length); // Always displays 100
        }
    });
```

**Comment by hrivera2014** [comment]
In regard of the last paragraph indeed are, up to 180 inquiries to the server in a 15 minutes window.
