### ISSUE TITLE
More than 140 characters?

### ISSUE THREAD

**Issue by fancyplants** [desmondmorris/node-twitter#266]
Where in the source code does it not allow any tweets over 140 characters? No string over 140 characters I've inputted into the API don't post at all.

**Comment by mrksutter** [comment]
Are you still having this issue? Twitter had not yet rolled out the 280 character limit when this issue was opened.

**Comment by fancyplants** [comment]
You seem to be absolutely right, Twitter now accepts 280 characters from its API. Sorry for the confusion, and keep up the amazing work!
