### ISSUE TITLE
how to put the text in retweet? 

### ISSUE THREAD

**Issue by danielaraujorn** [desmondmorris/node-twitter#285]
the param status is not working

**Comment by peterpme** [comment]
@danielaraujorn see https://github.com/Preposterous/twitter-lite and open an issue there if you're having trouble. Folks will help :)

**Comment by oceanbyte-deprecated** [comment]
You can use the `attachment_url` for that purpose (though this will not increase the retweet counter): 

```
// url looks like this: https://twitter.com/username/status/903615884664725505
client.post('statuses/update', {status: msg, attachment_url: url},  function(error, tweet, response) {});
```
