### ISSUE TITLE
post /lists/members/create_all & lists/members/create

### ISSUE THREAD

**Issue by maxaussprung** [desmondmorris/node-twitter#289]
when i'm trying to add members to a list, i'm getting {code: 34, message: "Sorry, that page does not exist."}

```
client
        .post("lists/members/create_all", {
          list_id: id,
          screen_name: temparray.toString()
        })
        .catch(function(err) {
          console.log(err[0]);
        }); 
```
Has someone a similar experience or a fix for me? thx

**Comment by peterpme** [comment]
@max2max1 see https://github.com/Preposterous/twitter-lite
