### ISSUE TITLE
How to get long link , not t.co 

### ISSUE THREAD

**Issue by zeing** [desmondmorris/node-twitter#290]
How to get long link , not ( t.co )  from tweet when  streaming

**Comment by peterpme** [comment]
@zeing https://github.com/Preposterous/twitter-lite

**Comment by zeing** [comment]
@peterpme how to fix it in your twitter-lite

**Comment by valeriabarros** [comment]
I don't know if the results are different in the stream, but through search, for each tweet in the list, we have the following structure:
statuses.entities.URLs (array) => If there's it's a display and expanded_url, that is not shortened.

maybe that's what you're looking for =]

**Comment by zeing** [comment]
@valeriabarros  yes , i use statuses.entities.URLs as []
