### ISSUE TITLE
TypeScript types (declaration file)

### ISSUE THREAD

**Issue by nunoarruda** [desmondmorris/node-twitter#309]
Is there a declaration file somewhere for this project? I can't seem to find it anywhere.

I've tried `npm install @types/twitter` but that's a declaration file Twitter for Websites (npmjs.com/package/@types/twitter)

**Comment by conatus** [comment]
@nunoarruda 

Did you have any luck finding this?

**Comment by nunoarruda** [comment]
No, no luck. We could create a definition file ourselves and put it on DefinitelyTyped but this project looks to be abandoned so I'm not sure if it's worth the trouble.

**Comment by conatus** [comment]
@desmondmorris 

Would it be fair to say this library is now unmaintained? Thanks for all your work on this so far!

**Comment by abraham** [comment]
I've been using https://github.com/ttezel/twit and while the `@types/twit` definitions have needed a couple of minor updates it's worked well.

**Comment by conatus** [comment]
Thanks @abraham for the recommendation!

**Comment by monsieurnebo** [comment]
For your information, the @types related to this project (`node-twitter`) seem now [available through DefinitlyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/fbec64b522edffb46124e548eae9d1a056094a9d/types/twitter/index.d.ts).

However, it lacks of "tweet type" (and more). This repo seems to have up-to-date API V2 @types:
https://github.com/PLhery/node-twitter-api-v2/tree/master/src/types/v2
