### ISSUE TITLE
Null, is a object!

### ISSUE THREAD

**Issue by alejonext** [desmondmorris/node-twitter#31]
[Null, is a object](https://github.com/desmondmorris/node-twitter/blob/master/lib/twitter.js#L983)

**Comment by alejonext** [comment]
@gasi  well.. OK!! :)

**Comment by desmondmorris** [comment]
@alejonext @gasi I don't think this is still an issue.  The endpoint helper methods have been deprecated [for a few reasons](https://github.com/desmondmorris/node-twitter#migrating-to-1x).

**Comment by alejonext** [comment]
@desmondmorris However it is something to keep in mind.
