### ISSUE TITLE
 [ { code: 32, message: 'Could not authenticate you.' } ] 

### ISSUE THREAD

**Issue by Vladinho10** [desmondmorris/node-twitter#311]
const client = new Twitter({
            consumer_key: consumerKey,
            consumer_secret: secretKey,
            access_token_key: accessToken,
            access_token_secret
        });
        //
        var params = {
            include_email: true,
            // default_profile_image: true
        };

        client
            .get('account/verify_credentials', params)
            .then(r => console.log(r))
            .catch(err => console.err(err));

Why it gives error?

**Comment by JonathanLoscalzo** [comment]
did you solve it? 
The same to me, I thought that was an space on a key, but I write it by hand and it is the same.

I activated twitter-envs and select my app, but I couldn't found another possible mistake.

**Comment by dandv** [comment]
Was there a `!` character anywhere in the payload? We've fixed that problem recently in [twitter-lite](https://github.com/draftbit/twitter-lite) and now any DM can be sent.

**Comment by MarcGodard** [comment]
Same issue here

**Comment by ibrokemycomputer** [comment]
I switched to https://www.npmjs.com/package/twit and it worked like a charm. The switch took about 45 seconds lol. Probably a header issue but ¯\_(ツ)_/¯

**Comment by MarcGodard** [comment]
I also switched... This repo is dead.

**Comment by Vladinho10** [comment]
I solved this issue

const client = new Twitter({
   consumer_key: consumerKey, (static value, from your Twitter app)
   consumer_secret: secretKey, (static value, from your Twitter app)
   access_token_key: accessToken, (dynamic value, from each user)
   access_token_secret: accessTokenSecret (dynamic value, from each user)
});
            const data = await client.get('https://api.twitter.com/1.1/account/verify_credentials.json', {
                include_email: true,
                skip_status: true
            });

thank you all !
