### ISSUE TITLE
throw er; // Unhandled 'error' event

### ISSUE THREAD

**Issue by zettam** [desmondmorris/node-twitter#40]
Here is my current code after require and create the twit object

    twit.stream('statuses/filter', {track:"love"}, function(stream) {
        stream.on('data', function(data) {
            console.log(data.entities.media[0].media_url)
        });
    });

I should be getting many ´undefined´ however all I get is the error in the title.

**Comment by desmondmorris** [comment]
Thanks @sbehrends - I am going to add this to the example and give you authorship.

**Comment by sbehrends** [comment]
Nice job :+1:
