### ISSUE TITLE
Async Twitter

### ISSUE THREAD

**Issue by krazydriver** [desmondmorris/node-twitter#41]
I'm using this module, and I need it to be asynchronous (for example: on Search) , there's a way to do this ?

**Comment by desmondmorris** [comment]
@krazydriver all of the requests are async.  You must pass a callback to the request functions.  The format is as follows:

```javascript
client.get(path, params, callback);
client.post(path, params, callback);
client.stream(path, params, callback);
```

**Search example:**
```javascript
client.get('search/tweets', {q: 'node.js'}, function(error, tweets, response){
   console.log(tweets);  // This happens after the request has finished
});
````
