### ISSUE TITLE
Image posting?

### ISSUE THREAD

**Issue by zettam** [desmondmorris/node-twitter#54]
Is it possible to post images with the current system?

**Comment by technotip** [comment]
I'm using:

Twitter REST API 1.1 /media/upload
Node.js
npm node-twitter 
Client Side: angular.js (not relevant to the example am posting below)

I guess 'node-twitter' uses base URL as api.twitter.com but for media upload the base URL is upload.twitter.com - Am not 100% sure about how 'node-twitter' package handles all these. But after working with it for sometime I feel it's REST API base URL is set as api.twitter.com

router.get('/api/media/upload', function(req, res){
    var fs = require('fs');
    twit.post('/media/upload', {media: fs.readFileSync('C:/Users/Satish/Downloads/243515_183060768410422_4955904_o.jpg', { encoding: 'base64' })}, function(error, params, response){
            if(error) console.log(error);
            else {
           twit.post('/statuses/update', {status: 'hello world!', media_ids: [params.media_id]}, function(error, params, response){
          console.log(params);
          res.json(params);
      });
       }
  });
});

But this code is throwing error, stating - 404, page does not exist. My guess is, 'node-twitter' is considering api.twitter.com as base URL for /media/upload too. If I replace '/media/upload' with full URL 'https://upload.twitter.com/1.1/media/upload' still I get the same error message.

[ Most of the articles online are written for deprecated POST statuses/update_with_media ]

**Comment by desmondmorris** [comment]
@technotip it was exactly that.  The latest release switches the base URL for the media/upload endpoint.   Give it a shot.  I have a feeling we may need to change the Content-Type too.

**Comment by yousifh** [comment]
I have been able to use the media/upload endpoint to upload images successfully, but I'm not able to post a tweet using the media_ids property. I tried switching between using media_id and media_id_string and still not able to tweet with an image. Error message I'm getting from twitter is code 32:	"Could not authenticate you". I'm wondering if this might have something to do with Content-Type or if I'm failing due to a mistake in my code.

**Comment by technotip** [comment]
@desmondmorris  Thanks ..I was using the older version of the package, so was not able to make it work :)

@yousifh Use media_id_string  of media/upload itself and pass it to media_ids parameter of /statuses/update as comma separated value. And it'll work. :+1:

**Comment by yousifh** [comment]
@technotip That's what I'm trying at the moment and getting the authentication error. Are you doing anything differently? 
```javascript
var image = fs.readFileSync('test.jpeg', {encoding: 'base64'});

client.post('media/upload', {media: image}, function(err, data, res) {
	if (err) console.log(err);
	console.log(data);
	client.post('statuses/update', {status: 'test picture', media_ids: [data.media_id_string]}, function(err, params, res) {
		if (err) console.log(err);
		console.log(params);
	});
});
```

**Comment by technotip** [comment]
Use this instead: (small change!)


var image = fs.readFileSync('test.jpeg', {encoding: 'base64'});

client.post('media/upload', {media: image}, function(err, data, res) {
    if (err) console.log(err);
    console.log(data);
    client.post('statuses/update', {status: 'test picture', media_ids: data.media_id_string}, function(err, params, res) {
        if (err) console.log(err);
        console.log(params);
    });
});

**Comment by yousifh** [comment]
@technotip Ah, I see so the media_ids doesn't actually take an array. Yeah your change works, thanks.

**Comment by technotip** [comment]
ya, and if you have multiple images then comma separate it:

var img1 = 'abc1.jpg';
var img2 = 'abc2.jpg';
var img3 = 'abc3.jpg';

var image = img1+','+img2+','+img3;

client.post('media/upload', {media: image}, function(err, data, res) {
if (err) console.log(err);
console.log(data);
client.post('statuses/update', {status: 'test picture', media_ids: data.media_id_string}, function(err, params, res) {
if (err) console.log(err);
console.log(params);
});

and it'll work for multiple image posting .. hope that helps :)

**Comment by desmondmorris** [comment]
Thanks @technotip.  I will add this to the examples

**Comment by joshmarinacci** [comment]
Question. Do I pass file paths to the media parameter or do I need to read them in as base64 and pass the blobs? For multiple images would I concatenate the blobs with commas?

Thanks.

**Comment by anand171** [comment]
How can I tweet an image that is on s3 bucket not in local folder of project?

var image = fs.readFileSync('S3 bucket url', {encoding: 'base64'});
client.post('media/upload', {media: image}, function(err, data, res) {})

**Comment by nandy48072** [comment]
> Use this instead: (small change!)
> 
> var image = fs.readFileSync('test.jpeg', {encoding: 'base64'});
> 
> client.post('media/upload', {media: image}, function(err, data, res) {
> if (err) console.log(err);
> console.log(data);
> client.post('statuses/update', {status: 'test picture', media_ids: data.media_id_string}, function(err, params, res) {
> if (err) console.log(err);
> console.log(params);
> });
> });

This success for send tweet but image upload not working
