### ISSUE TITLE
Add a timeout for the request

### ISSUE THREAD

**Issue by RainHeart257** [desmondmorris/node-twitter#66]
Hello!

I have been testing the library with a horrible Internet connection. The result is that the library blocks the application process waiting for a response from twitter (that never comes...)

Could you add a timeout option to stop the request if there is no response? 

Thanks

**Comment by desmondmorris** [comment]
@RainHeart257 You can pass the `timeout` option as a value in the `request_options` object in the constructor.

```javascript
var client = new Twitter({
  request_options: {
    "timeout": 5000
  }
});
```

Thsi module relies on [Request](http://github.com/request/request) and supports all of its options. https://github.com/request/request#requestoptions-callback

**Comment by RainHeart257** [comment]
Ok! Thank you very much

P.S. You could add this information to the main readme file ;-)

**Comment by desmondmorris** [comment]
:+1:
