### ISSUE TITLE
Streaming options

### ISSUE THREAD

**Issue by monxas** [desmondmorris/node-twitter#67]
Hi, I', using the streaming part of your package, and I got working the track option, but I can't seem to find any more options in the streaming api.
```javascript
client.stream('statuses/filter', {track: 'keyword'}, function(stream) {
```
instead of track, what other options can i use? stream all tweets from someone, or maybe get all tweets in a specific location...

**Comment by desmondmorris** [comment]
@monxas I believe its between track, follow and location.

See Streaming API docs: https://dev.twitter.com/streaming/reference/post/statuses/filter

**Comment by monxas** [comment]
I've been there before asking, but I couldn't manage to get any of those working, it would be great if you could post an example, thanks!

**Comment by saidimu** [comment]
Looking at the docs (https://github.com/desmondmorris/node-twitter/blob/master/lib/twitter.js#L179) it doesn't seem like this library supports streaming options other than `track`. 

So you can't filter by `language` or any of these [other](https://dev.twitter.com/streaming/overview/request-parameters#delimited) options.

**Comment by MohamadAtieh** [comment]
You can filter the language programmatically. And it makes sense that the Stream API doesn't support such parameters. If you save tweets into your local database, many of the tweet's fields do not return depending on how fast the stream is.

**Comment by saidimu** [comment]
What is the point of duplicating in your program what Twitter already does if you specify the language parameter? In addition, I bet Twitter's language detection is far more advanced, much faster and more reliable than anything most devs can implement in their own code.

**Comment by MohamadAtieh** [comment]
Duplicating what exactly? Language detection is not supported in the Stream and the way you can detect it is by capturing the `lang` key in the tweet. That's what I said.

**Comment by saidimu** [comment]
Here are [Twitter docs](https://dev.twitter.com/streaming/overview/request-parameters#language) on specifying the `language` parameter: 

```
only return Tweets that have been detected as being written in the specified languages.
```

**Comment by MohamadAtieh** [comment]
oh so the problem is this library

**Comment by saidimu** [comment]
Other libraries, for example [twat](https://www.npmjs.com/package/twat), support the options listed in the [Twitter docs](https://dev.twitter.com/streaming/overview/request-parameters):

* delimited
* stall_warnings
* filter_level
* language
* follow
* track
* locations
* count
* with
* replies
* stringify_friend_id

**Comment by desmondmorris** [comment]
@MohamadAtieh @monxas @saidimu all streaming request parameters are now available.
