### ISSUE TITLE
Noob Question - Search API

### ISSUE THREAD

**Issue by oliverbenns** [desmondmorris/node-twitter#68]
Hey! Apologies for the noob question here. At the minute I have this code and it's working well:
```
	twit.get('/search/tweets.json', {
		count: 50,
		q: '#hashtag -RT',
		result_type: 'popular'
	}
```

What I'd like to do is make use of the [query parameters](https://dev.twitter.com/rest/public/search) like 'since' and 'until' but I'm really not sure how to add this in. I thought it would be as simple as ` q: '#hashtag -RT since:2010-12-27' ` but I have come to no such luck.

If someone could point me in the right direction that would be superb!

**Comment by MohamadAtieh** [comment]
In the page:

**The Search API is not complete index of all Tweets, but instead an index of recent Tweets. At the moment that index includes between 6-9 days of Tweets.**

Your query takes you back to `2010-12-27`

**Comment by oliverbenns** [comment]
I don't truly understand. I want to make use of both `until:` and before:` as listed [here](https://dev.twitter.com/rest/public/search). 

I'm using `q: '#hashtag -RT until:2014-01-01'`  but it fails to retrieve any data.

**Comment by MohamadAtieh** [comment]
I am sure how the syntax should be, but try a date that doesn't go back more than 6-9 days. Check your date :)

**Comment by oliverbenns** [comment]
Ah I see what you mean! But this doesn't make logical sense. Why would they have until & before for the sake of 6 days. I've also seen plenty of sites that have gone back very far.

**Comment by desmondmorris** [comment]
@oliverbenns unfortunately, as @MohamadAtieh mentioned it is a limitation of the current offering from Twitter.  Take a look here: https://twittercommunity.com/t/new-limit-on-search-api-to-limit-tweets-less-than-a-week-please-help-is-there-any-way-to-search-tweets-with-a-hashtag-that-is-older-than-2-weeks/7710/4
