### ISSUE TITLE
Use tweet.id_str instead of tweet.id when replying to a tweet

### ISSUE THREAD

**Issue by arno-di-loreto** [desmondmorris/node-twitter#72]
I don't know if it's a bug but when replying to a tweet, the *in_reply_to_status_id* value must be *tweet.id_str* and not *tweet.id*.

var s = '@'+tweet.user.screen_name+ '  the answer...';
client.post('statuses/update', {in_reply_to_status_id: tweet.id_str, status: s},  function(error, tweet, response){...});

If you do not do this, the new tweet will not be a reply, the tweet.id is not taken into account.
And do not forget to include the '@'+tweet.user.screen_name in the status as explained in Twitter documentation.

**Comment by desmondmorris** [comment]
@arno-di-loreto its a known issue.  See: https://dev.twitter.com/overview/api/twitter-ids-json-and-snowflake
