### ISSUE TITLE
How to format search queries

### ISSUE THREAD

**Issue by basiclaser** [desmondmorris/node-twitter#74]
Hi there. Love this package. 

I'm not sure how to include multiple parameters to the REST API. 
I would like to search a particular users twitter feed for soundcloud and youtube links, 
so I believe I should include these parameters: 

from:user_name 
filter:links 
soundcloud OR youtube

But then I'm not surely exactly where to put these parameters

should it be in the "q" key object like this? 
 
    client.get('search/tweets', {q: "from:" +user_name " filter:links soundcloud OR youtube"},
    function(error, userObject, response){
     console.log(response); 
    });

Would you suggest achieving this goal a different way at all? thanks.

**Comment by desmondmorris** [comment]
@basiclaser yes, I believe your query is correct.  Its the callback that is incorrect.  The parameters are *error*, *data*, *response* in that order, with response being the full HTTP response and data being the API response.

```javascript
client.get('search/tweets', {q: "from:" +user_name " filter:links soundcloud OR youtube"},
function(error, data, response){
 console.log(data); 
});
````

**Comment by basiclaser** [comment]
Thanks so much!
Just another little question, I'm attempting to log each of the tweets, let's say the default 15. 
My understanding is that statuses == tweets , right?

When I run "console.log(data);", I'm presented with "count: 15," near the bottom of the JSON object.
When I then try "console.log(data.statuses);" and "console.log(data.statuses[0]);" I log what I assume is the first tweet, or "status". 

However, incrementing the "statuses[x]" yields "undefined" above 0. 

How can I log the other tweets or "statuses" in the object?

**Comment by desmondmorris** [comment]
@basiclaser looks like statuses is an array.  You can use a look to iterate through them.  So something like:

```javascript
client.get('search/tweets', {q: "from:" +user_name " filter:links soundcloud OR youtube"},
function(error, data, response){
 console.log(data); 
  // First make sure statuses is available
  if (typeof data.statuses !== 'undefined') {
    // Use a for loop to iterate over the array
    for (var i = 0; i< data.statuses.length; i++) {
      // Log each status
      console.log(data.statuses[i]);
    } 
  }
});
```

**Comment by desmondmorris** [comment]
@basiclaser I just re-read your ask - can you post the query you are using?

**Comment by basiclaser** [comment]
Hi desmond, 
Thanks, you got me a step closer to accessing all the tweets. 

This is my query. 

    client.get('search/tweets', {q: "from:basiclaser"},
      function(error, data, response){
        if (typeof data.statuses !== 'undefined') {
          // Use a for loop to iterate over the array
          for (var i = 0; i< data.statuses.length; i++) {
            // Log each status
            console.log(data.statuses[i].text);
          }
        }
    });

It strangely only prints out 5 results, (I checked with console.log(data.statuses.length)). I would expect it to print out the default 15, as I have tweeted over the default value of 15. 

Interestingly if I add any other parameters, such as  "count: 30 result_type: recent", the length of statuses drops to 0.

Even more interestingly, if i remove "from me" as a parameter and just specify "count: 47" for example, i receive the default 15. 

Sorry for so many observations. I hope you can help me get some clarity out of this madness!

*To reiterate, I'd like to collect a number of a users recent tweets, then perform some operations on the data afterwards.

**Comment by basiclaser** [comment]
Ah i see, I think I should have been splitting the parameters into key:"value" pairs like this.

    client.get('search/tweets', {count: 40},
      function(error, data, response){
        data.statuses.forEach(function(tweet){
          console.log(tweet.text)
        })
        console.log(data.statuses.length);
    });

This returns 40 tweets. 
However, if I add the 'from' parameter in the newly discovered correct format, it drops back to 5 tweets. I have over 600 tweets so it should manage 40. . . 
Here's my latest..

    client.get('search/tweets', {count: 40, from:"basiclaser"},
      function(error, data, response){
        data.statuses.forEach(function(tweet){
          console.log(tweet.text)
        })
        console.log(data.statuses.length);
    });

**Comment by desmondmorris** [comment]
@basiclaser so, I think you are seeing quirks in the search API itself.  The search API will only return results from the last x days.  See #68 

For this ask, you may be better off with the [statuses/user_timeline](https://dev.twitter.com/rest/reference/get/statuses/user_timeline) endpoint:

```javascript
client.get('statuses/user_timeline', {screen_name: 'basiclaser'},
  function(error, data, response){
    console.log(data);
});
````

**Comment by basiclaser** [comment]
Fascinating, thankyou!
