### ISSUE TITLE
npm ERR! Error: No compatible version found: request@'^2.51.0'

### ISSUE THREAD

**Issue by mohdasif2294** [desmondmorris/node-twitter#76]
![error_twitter](https://cloud.githubusercontent.com/assets/5481219/6677643/f6418d8a-cc57-11e4-9969-b2f8e2b99ecc.png)

I could not install the twitter api.
please help

**Comment by desmondmorris** [comment]
@mohdasif2294 try updating npm.  `npm install -g npm`

**Comment by mohdasif2294** [comment]
Sorry, my bad. 
Re-installing the npm worked.
