### ISSUE TITLE
Tracking all tweets

### ISSUE THREAD

**Issue by FilipLukac** [desmondmorris/node-twitter#78]
Hello, Its possible to track all tweets ? something like ...{track:'*'} ?

**Comment by iamstarkov** [comment]
what do you mean by "tracking"?

**Comment by iamstarkov** [comment]
@Chipsi  ping

**Comment by Chipsi** [comment]
@iamstarkov I wanted to track all tweets around the world... image that situatio, when someone has posted tweet on twitter (doesnt matter which hashtag), I want to receive this tweet.

**Comment by iamstarkov** [comment]
Im pretty sure it is impossible, but you can ask once again in twitter api forum https://twittercommunity.com/. pretty sure this issue can be closed

**Comment by varmint09** [comment]
I think he means polling a twitter account for when it posts an update. This shouldn't be added to this library as its a cron task or something similar.

+1 for closing this.

**Comment by iamstarkov** [comment]
polling still will not return him all the tweets, because of 3200 limit

**Comment by deltamualpha** [comment]
Yeah, twitter doesn't make it possible to get access to *all* real-time tweets without a license agreement and a lot of hoops. And not that it matters -- there's no way most people could properly handle that much data without a specialized application and storage backend. (the firehose API is just a sampling!)
