### ISSUE TITLE
Could I destroy stream object ? Or destroy stream listner ? 

### ISSUE THREAD

**Issue by FilipLukac** [desmondmorris/node-twitter#80]
Hello, I've created stream like....

client.stream('statuses/filter',....., function(stream){
     .....

    // CAN I DESTROY LISTENER TO STREAM HERE ? 
});

**Comment by adeelhussain** [comment]
Hi,
 If we see inside the module then, there is a method namely "stream.destroy", it will destroy the current stream

**Comment by desmondmorris** [comment]
+1 @adeelhussain.  `stream.destroy()` should do the truck
