### ISSUE TITLE
index.js program not running

### ISSUE THREAD

**Issue by DKH202** [desmondmorris/node-twitter#83]
I have Twitter installed via npm and created the index.js file below.  When I run node index.js in the console I'm not getting any response.  I've filled in the proper keys and tokens.

var Twitter = require('twitter');

var client = new Twitter({
  consumer_key: process.env.TWITTER_CONSUMER_KEY,
  consumer_secret: process.env.TWITTER_CONSUMER_SECRET,
  access_token_key: process.env.TWITTER_ACCESS_TOKEN_KEY,
  access_token_secret: process.env.TWITTER_ACCESS_TOKEN_SECRET,
});

client.stream('statuses/filter', {track: 'nyc'},  function(stream){
  stream.on('data', function(tweet) {
    console.log(tweet.text);
  });

  stream.on('error', function(error) {
    console.log(error);
  });
});

**Comment by ThomasCrvsr** [comment]
Hello,

Maybe it's because there are no tweets containing "nyc" when you tested it. It happened to me sometimes.

**Comment by DKH202** [comment]
Ok gotcha, I think I've got this one figured out now.  Thanks!
