### ISSUE TITLE
Image uploading trickiness

### ISSUE THREAD

**Issue by joshwcomeau** [desmondmorris/node-twitter#88]
I've been stuck on image uploading today, the 'media' example given isn't working for me.

I found the following configuration **does** work:

```
client.post('media/upload', 
  { 
    media_data: fs.readFileSync('image.jpg', { encoding: 'base64' })
  }, 
  function(err, media, response){ // stuff here }
);
```

According to the twitter docs on the media/upload endpoint (https://dev.twitter.com/rest/reference/post/media/upload), you use 'media' for a binary string of image data, and 'media_data' for a base64 encoded one. For whatever, simply reading the image contents with readFile as binary and passing it to 'media' leads to an unspecified 500 error, but this works.

**Comment by parkerproject** [comment]
None seems to be working for me. I keep getting
[Error: HTTP Error: 400 Bad Request]

**Comment by desmondmorris** [comment]
@joshwcomeau your findings are correct, that is what the API expects.  We may want to update the example to show both cases.

@parkerproject Seems like your issue is related to #77
