### ISSUE TITLE
Stream gets 401 in all versions after to 1.1.0

### ISSUE THREAD

**Issue by jbrunken** [desmondmorris/node-twitter#89]
When I try and use the stream API with 1.2.x, I'm getting an immediate 401 error.    Rolling back to 1.1.0 resolves the 401 error.

**Comment by jbrunken** [comment]
Figured this out.   The config object no longer allows an array for the "follow" property.   The follow needs to be a comma delimited list of ids.

In other words, I had to change

{  follow: [123, 456, 789), track: ""}

to :

{ follow:"123,456,789", track: ""}

**Comment by Roach** [comment]
1.2 is not a valid API version...
